//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allotment
    {
        public string bid { get; set; }
        public int year { get; set; }
        public System.DateTime dateOfJoin { get; set; }
        public Nullable<System.DateTime> dateOfLeave { get; set; }
        public int hostelBlock { get; set; }
        public int roomNum { get; set; }
        public int slNum { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Room Room { get; set; }
    }
}
