//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessBill()
        {
            this.MessTransactions = new HashSet<MessTransaction>();
        }
    
        public long billNum { get; set; }
        public System.DateTime dateOfDeclaration { get; set; }
        public int numDays { get; set; }
        public int month { get; set; }
        public string bid { get; set; }
        public Nullable<int> year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessTransaction> MessTransactions { get; set; }
        public virtual Student Student { get; set; }
    }
}
